# Generated by Django 4.2 on 2023-04-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_material_name', models.CharField(max_length=45)),
                ('iron_concentration', models.CharField(max_length=11)),
                ('silicon_concentration', models.CharField(max_length=11)),
                ('aluminum_concentration', models.CharField(max_length=11)),
                ('calcium_concentration', models.CharField(max_length=11)),
                ('sulfur_concentration', models.CharField(max_length=11)),
            ],
        ),
    ]
