# Generated by Django 4.2 on 2023-04-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_entries_delete_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=40)),
                ('raw_material_name', models.CharField(max_length=40)),
                ('iron_concentration', models.CharField(max_length=10)),
                ('silicon_concentration', models.CharField(max_length=10)),
                ('aluminum_concentration', models.CharField(max_length=10)),
                ('calcium_concentration', models.CharField(max_length=10)),
                ('sulfur_concentration', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Entries',
        ),
    ]
