# Generated by Django 4.2 on 2023-05-31 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_alter_record_aluminum_concentration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concentration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=10)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.record')),
            ],
        ),
    ]
