# Generated by Django 4.2 on 2023-05-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_concentration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concentration',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
