# Generated by Django 4.2 on 2023-06-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0006_alter_concentration_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Concentration',
        ),
    ]
